<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="2" total="3" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-07-21T18:08:02 IST" name="TestSuite" finished-at="2025-07-21T18:08:11 IST" duration-ms="8655">
    <groups>
      <group name="regression">
        <method signature="TestCase_1.TestUserRegistration()[pri:0, instance:Testcases.TestCase_1@403f0a22]" name="TestUserRegistration" class="Testcases.TestCase_1"/>
      </group> <!-- regression -->
      <group name="master">
        <method signature="TestCase_1.TestUserRegistration()[pri:0, instance:Testcases.TestCase_1@403f0a22]" name="TestUserRegistration" class="Testcases.TestCase_1"/>
      </group> <!-- master -->
    </groups>
    <test started-at="2025-07-21T18:08:02 IST" name="windows-chrome" finished-at="2025-07-21T18:08:11 IST" duration-ms="8655">
      <class name="Testcases.TestCase_1">
        <test-method is-config="true" signature="setup(java.lang.String,java.lang.String)[pri:0, instance:Testcases.TestCase_1@403f0a22]" started-at="2025-07-21T18:08:03 IST" name="setup" finished-at="2025-07-21T18:08:06 IST" duration-ms="3715" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[window]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="TestUserRegistration()[pri:0, instance:Testcases.TestCase_1@403f0a22]" started-at="2025-07-21T18:08:06 IST" name="TestUserRegistration" finished-at="2025-07-21T18:08:10 IST" duration-ms="4074" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[not matching expected [Your Account Has Been Created!...] but found [Your Account Has Been Created!]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: not matching expected [Your Account Has Been Created!...] but found [Your Account Has Been Created!]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at Testcases.TestCase_1.TestUserRegistration(TestCase_1.java:64)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestUserRegistration -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:Testcases.TestCase_1@403f0a22]" started-at="2025-07-21T18:08:11 IST" name="teardown" finished-at="2025-07-21T18:08:11 IST" duration-ms="297" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- Testcases.TestCase_1 -->
    </test> <!-- windows-chrome -->
  </suite> <!-- TestSuite -->
</testng-results>
